### ISSUE TITLE
Setup the application to use GetText

### ISSUE THREAD

**Issue by doomspork** [elixirschool/admissions#7]
We have a wonderful team of translators, we should setup the application to allow translation of the few pages.  This will further serve as an example for folks coming to Elixir/Phoenix on how to leverage gettext.

Thoughts @gemantzu?

**Comment by gemantzu** [comment]
I have not had the chance to play with gettext yet, this will be a good opportunity for me as well to get to know it.

**Comment by doomspork** [comment]
Anyone from @elixirschool/developers or @elixirschool/translators who's interested in helping get this project setup with gettext is more than welcomed.  After all this provides something for all of us 👍

**Comment by doomspork** [comment]
Closing because now use `gettext` we just have no translations at this time.
